// emailJsConfig.js
const EMAILJS_CONFIG = {
    SERVICE_ID1: import.meta.env.VITE_EMAILJS_SERVICE_ID1,
    SERVICE_ID2: import.meta.env.VITE_EMAILJS_SERVICE_ID2,
    TEMPLATE_ID_ALUNO: import.meta.env.VITE_EMAILJS_TEMPLATE_ID_ALUNO,
    TEMPLATE_ID_PROFESSOR: import.meta.env.VITE_EMAILJS_TEMPLATE_ID_PROFESSOR,
    TEMPLATE_ID_VANTAGEM: import.meta.env.VITE_EMAILJS_TEMPLATE_ID_VANTAGEM,
    PUBLIC_KEY1: import.meta.env.VITE_EMAILJS_PUBLIC_KEY1,
    PUBLIC_KEY2: import.meta.env.VITE_EMAILJS_PUBLIC_KEY2,
  };
  
  export default EMAILJS_CONFIG;