spring:
  datasource:
    # Monta a URL JDBC a partir das variáveis padrão do Postgres (compatível com Railway)
    url: jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:railway}${DB_PARAMS:}
    driver-class-name: org.postgresql.Driver
    username: ${PGUSER:postgres}
    password: ${PGPASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      fail-on-empty-beans: false
    default-property-inclusion: non_null

server:
  port: 8080

logging:
  level:
    com.sistemaaluguel: DEBUG
